version: 0.2

env:
  variables:
    IMAGE_NAME: core-gateway
    IMAGE_TAG: latest

phases:
  install:
    commands:
      - echo Checking AWS CLI and Docker
      - aws --version
      - docker --version
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=$AWS_DEFAULT_REGION
      - REPO_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}
      - echo ACCOUNT_ID=$ACCOUNT_ID REGION=$REGION REPO_URI=$REPO_URI
      - aws ecr get-login-password --region ${REGION} > /tmp/ecrpass.txt
      - docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com < /tmp/ecrpass.txt

  build:
    commands:
      - echo Docker build
      - docker build -f Dockerfile.core-gateway -t ${IMAGE_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPO_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - echo Docker push
      - docker push ${REPO_URI}:${IMAGE_TAG}
      - printf "IMAGE_URI=%s\n" "${REPO_URI}:${IMAGE_TAG}" > image-uri.txt
      - echo Done

artifacts:
  files:
    - image-uri.txt
