version: 0.2

phases:
  install:
    commands:
      - corepack enable
      - corepack prepare yarn@4.9.4 --activate
      - yarn config set nodeLinker node-modules
      # Instalar solo lo necesario del workspace (prod)
      - yarn workspaces focus @sevens/core-gateway --production
      # Añadimos herramientas de build si hace falta
      - yarn add -D typescript ts-node
      # Añadimos el runtime adapter para Lambda+Fastify
      - yarn add @fastify/aws-lambda
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - cd apps/core-gateway
      - yarn build
      - cd ../..
      # Empaquetamos solo lo necesario para Lambda
      - zip -r core-gateway.zip \
          apps/core-gateway/dist \
          apps/core-gateway/package.json \
          node_modules/@nestjs \
          node_modules/@prisma \
          node_modules/.prisma \
          node_modules/rxjs \
          node_modules/reflect-metadata \
          node_modules/@fastify
  post_build:
    commands:
      - echo "Build finished, checking package size..."
      - du -sh core-gateway.zip || true
      - unzip -l core-gateway.zip | head -20 || true

artifacts:
  files:
    - core-gateway.zip
