version: 0.2

phases:
  install:
    commands:
      - corepack enable
      - corepack prepare yarn@4.9.4 --activate
      # Instalamos solo dependencias de producción
      - yarn config set nodeLinker node-modules
      - yarn workspaces focus @sevens/core-gateway --production
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - cd apps/core-gateway
      - yarn build
      - cd ../..
      # Empaquetamos solo dist + package.json + dependencias necesarias
      - zip -r core-gateway.zip apps/core-gateway/dist \
          apps/core-gateway/package.json \
          node_modules/@nestjs \
          node_modules/@prisma \
          node_modules/.prisma
  post_build:
    commands:
      - echo "Build finished, checking package size..."
      - du -sh core-gateway.zip
      - unzip -l core-gateway.zip | head -20

artifacts:
  files:
    - core-gateway.zip
