version: 0.2

phases:
  install:
    commands:
      # Forzamos Yarn Classic
      - npm install -g yarn
      # Instalamos dependencias desde la raíz del monorepo
      - yarn --cwd $CODEBUILD_SRC_DIR install
  pre_build:
    commands:
      # Obtenemos la conexión a RDS desde Secrets Manager
      - export DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id core/dev/DATABASE_URL --query SecretString --output text)
  build:
    commands:
      # Ejecutamos migraciones Prisma contra RDS Proxy
      - npx prisma migrate deploy --schema=packages/db/schema.prisma
