version: 0.2

phases:
  install:
    commands:
      - corepack enable
      - corepack prepare yarn@4.9.4 --activate
      - yarn install --immutable
  pre_build:
    commands:
      - export DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id core/dev/DATABASE_URL --query SecretString --output text)
  build:
    commands:
      - cd packages/db
      - npx prisma migrate deploy --schema=prisma/schema.prisma
         - node prisma/seed.mjs
