version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "📦 Instalando Yarn..."
      - npm install -g corepack
      - corepack enable
      - echo "📦 Instalando dependencias del monorepo..."
      - yarn install --immutable
  build:
    commands:
      - echo "🔨 Compilando todo el monorepo..."
      - yarn build:all
      - echo "🚀 Desplegando infraestructura con CDK..."
      - yarn cdk:synth
      - npx cdk deploy CoreStack --require-approval never
artifacts:
  files:
    - '**/*'
