version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "📦 Instalando pnpm..."
      - npm install -g pnpm
      - pnpm config set store-dir /root/.pnpm-store
      - echo "📦 Instalando jq para procesar JSON..."
      - apt-get update -y && apt-get install -y jq
      - echo "📦 Instalando dependencias del monorepo..."
      - pnpm install --frozen-lockfile
      
  build:
    commands:
      # 1. COMPILAR TODO EL CÓDIGO
      - echo "🔨 Compilando todo el código del monorepo (frontend y backend)..."
      - pnpm run build

      # 2. DESPLEGAR INFRAESTRUCTURA
      - echo "🚀 Desplegando infraestructura con CDK..."
      - pnpm --filter @sevens/cdk-core exec cdk deploy CoreStack --require-approval never --outputs-file cdk-outputs.json
      
      # 3. MIGRAR BASE DE DATOS
      - echo "⚙️ Iniciando migración de base de datos..."
      - export DB_SECRET_ARN=$(jq -r '.CoreStack.DbSecretArn' infra/cdk-core/cdk-outputs.json)
      - export DATABASE_HOST=$(jq -r '.CoreStack.RdsProxyEndpoint' infra/cdk-core/cdk-outputs.json)
      - echo "   -> Obteniendo credenciales de la base de datos..."
      - echo "DB_SECRET_ARN: $DB_SECRET_ARN"
      - 'export DB_SECRET=$(aws secretsmanager get-secret-value --secret-id $DB_SECRET_ARN --query SecretString --output text)'
      - echo "DB_SECRET: $DB_SECRET"
      - export DB_USER=$(echo $DB_SECRET | jq -r .username)
      - export DB_PASS=$(echo $DB_SECRET | jq -r .password)
      - export DATABASE_URL="postgresql://$DB_USER:$DB_PASS@$DATABASE_HOST:5432/postgres"
      - echo "   -> Ejecutando Prisma Migrate..."
      - npx prisma migrate deploy --schema packages/db/prisma/schema.prisma

      # 4. PUBLICAR FRONTEND
      - echo "🎨 Iniciando publicación del frontend..."
      - export FRONTEND_BUCKET=$(jq -r '.CoreStack.FrontendBucketName' infra/cdk-core/cdk-outputs.json)
      - echo "   -> Sincronizando archivos con S3 (la compilación ya se hizo)..."
      - aws s3 sync dist s3://$FRONTEND_BUCKET/ --delete

cache:
  paths:
    - '/root/.pnpm-store'
