version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "📦 Instalando pnpm..."
      - npm install -g pnpm
      - pnpm config set store-dir /root/.pnpm-store
      - echo "📦 Instalando dependencias del monorepo..."
      - pnpm install --frozen-lockfile
  build:
    commands:
      - echo "🔨 Compilando todo el monorepo..."
      - pnpm run build:all
      - echo "🚀 Desplegando infraestructura con CDK..."
      - pnpm run cdk:synth
      - pnpm run cdk:deploy -- CoreStack --require-approval never
cache:
  paths:
    - '/root/.pnpm-store'
artifacts:
  files:
    - '**/*'
