version: 0.2

phases:
  install:
    commands:
      - corepack enable
      - corepack prepare yarn@4.9.4 --activate
      - yarn config set nodeLinker node-modules
      # Instalar dependencias clásicas (incluye dev, no solo prod)
      - yarn workspaces focus @sevens/core-gateway --all --production false
      - yarn add -D typescript
  build:
    commands:
      - cd apps/core-gateway
      - yarn build
      - zip -r ../../core-gateway.zip dist node_modules package.json
artifacts:
  files:
    - core-gateway.zip
