version: 0.2

phases:
  install:
    commands:
      - corepack enable
      - corepack prepare yarn@4.9.4 --activate
      - yarn config set nodeLinker node-modules
      # Instalamos también typescript y nest-cli aunque sean devDependencies
      - yarn add -D typescript @nestjs/cli
      - yarn workspaces focus @sevens/core-gateway --all --production false
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - cd apps/core-gateway
      - yarn build
      - cd ../..
      - zip -r core-gateway.zip apps/core-gateway/dist node_modules apps/core-gateway/package.json
artifacts:
  files:
    - core-gateway.zip
