version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "📦 Instalando pnpm..."
      - npm install -g pnpm
      - echo "🔧 Configurando Git..."
      - git config --global user.name "AWS CodeBuild"
      - git config --global user.email "codebuild@amazon.com"
  build:
    commands:
      - echo "🚨 Forzando la actualización del pnpm-lock.yaml..."
      # Añadimos --no-frozen-lockfile para permitir que pnpm modifique el lockfile en un entorno de CI
      - pnpm install --no-frozen-lockfile
      - echo "🔍 Verificando si el lockfile ha cambiado..."
      - |
        if [[ -z $(git status --porcelain pnpm-lock.yaml) ]]; then
          echo "✅ pnpm-lock.yaml ya está actualizado. No se necesitan cambios."
        else
          echo "⬆️ El pnpm-lock.yaml ha sido modificado. Subiendo cambios al repositorio..."
          - BRANCH_NAME=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}
          - git add pnpm-lock.yaml
          - git commit -m "chore(ci): actualizar pnpm-lock.yaml desde CodeBuild"
          - git push origin HEAD:$BRANCH_NAME
          echo "🚀 El archivo pnpm-lock.yaml ha sido actualizado en la rama $BRANCH_NAME."
        fi
