version: 0.2

env:
  variables:
    IMAGE_NAME: core-gateway
    IMAGE_TAG: latest

phases:
  install:
    commands:
      - echo "Inicializando variables y login en ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=$(aws configure get region)
      - REPO_URI="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_NAME}"
      - echo "ACCOUNT_ID=$ACCOUNT_ID REGION=$REGION REPO_URI=$REPO_URI"
      - aws ecr describe-repositories --repository-names "${IMAGE_NAME}" >/dev/null 2>&1 || aws ecr create-repository --repository-name "${IMAGE_NAME}"
      - aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

  build:
    commands:
      - echo "Construyendo imagen Docker desde Dockerfile.core-gateway..."
      - docker build -f Dockerfile.core-gateway -t "${IMAGE_NAME}:${IMAGE_TAG}" .
      - docker tag "${IMAGE_NAME}:${IMAGE_TAG}" "${REPO_URI}:${IMAGE_TAG}"

  post_build:
    commands:
      - echo "Subiendo imagen a ECR..."
      - docker push "${REPO_URI}:${IMAGE_TAG}"
      - echo "IMAGE_URI=${REPO_URI}:${IMAGE_TAG}" > image-uri.txt
artifacts:
  files:
    - image-uri.txt
