version: 0.2

phases:
  install:
    commands:
      # Instalamos Yarn Classic (1.x)
      - npm install -g yarn
      # Nos aseguramos de estar en la raíz del monorepo
      - cd $CODEBUILD_SRC_DIR
      # Instalamos dependencias con workspaces (sin frozen-lockfile, porque rompe con workspace:*)
      - yarn install
  pre_build:
    commands:
      # Recuperamos la conexión desde Secrets Manager
      - export DATABASE_URL=$(aws secretsmanager get-secret-value --secret-id core/dev/DATABASE_URL --query SecretString --output text)
  build:
    commands:
      # Ejecutamos migraciones Prisma contra RDS Proxy
      - npx prisma migrate deploy --schema=packages/db/schema.prisma
