export const AVAILABLE_VIEWS: { key: string, label: string }[] = [
    { key: 'products', label: 'Productos' },
    { key: 'tasks', label: 'Tareas' },
    { key: 'proyectos', label: 'Proyectos' },
    { key: 'taskSchemas', label: 'Esquemas de Trabajo' },
    { key: 'contentRecipes', label: 'Recetas de Contenido' },
    { key: 'promptTemplates', label: 'Plantillas de IA' },
    { key: 'aiSettings', label: 'Ajustes de IA' },
    { key: 'pvprMatrix', label: 'Matriz de PVPR' },
    { key: 'pricingRules', label: 'Reglas de Precios' },
    { key: 'manufacturing', label: 'Visión Fabricación' },
    { key: 'purchaseOrders', label: 'Pedidos Fabricación' },
    { key: 'batches', label: 'Lotes' },
    { key: 'deliveryNotes', label: 'Albaranes' },
    { key: 'invoices', label: 'Facturas' },
    { key: 'competitorProducts', label: 'Productos Competencia' },
    { key: 'competitorBrands', label: 'Marcas Competencia' },
    { key: 'countries', label: 'Países' },
    { key: 'platforms', label: 'Plataformas' },
    { key: 'videos', label: 'Videos' },
    { key: 'etiquetas', label: 'Etiquetas' },
    { key: 'envases', label: 'Envases' },
    { key: 'ingredients', label: 'Ingredientes' },
    { key: 'productNotifications', label: 'Gestión Notificaciones' },
    { key: 'notes', label: 'Notas' },
    { key: 'logs', label: 'Registro de Actividad' },
    { key: 'translationTerms', label: 'Términos Traducción' },
    { key: 'tickets', label: 'Atención Cliente' },
    { key: 'notifications', label: 'Dashboard Notificaciones' },
    { key: 'publicationStatus', label: 'Dashboard Estado Publicación' },
    { key: 'importExport', label: 'Centro de Publicación' },
];